# Generated by Django 4.2.1 on 2023-05-18 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_prix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PRIX €')),
                ('promo_date_on', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 10, 52, 38, 851242), null=True, verbose_name='DATE DEBUT')),
                ('promo_date_end', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 10, 52, 38, 851242), verbose_name='DATE FIN')),
                ('promo_remise', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=60, verbose_name='CATEGORIES')),
                ('produits', models.CharField(blank=True, max_length=60, verbose_name='PRODUITS')),
                ('descriptions', models.TextField(max_length=400, verbose_name='DESCRIPTIONS')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PRIX €')),
                ('date', models.DateField(verbose_name='DATE')),
                ('images', models.ImageField(upload_to='images', verbose_name='PHOTOS')),
                ('promotions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.promo')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
