# Generated by Django 4.2.1 on 2023-06-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_promo_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='promotions',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='catalogue.promo'),
        ),
    ]
