# Generated by Django 4.2.1 on 2023-05-18 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_catalogue_promotions_promo_promotions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='promotions',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.catalogue', verbose_name='CATEGORIES'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 11, 57, 8, 661888), verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 11, 57, 8, 661888), null=True, verbose_name='DATE DEBUT'),
        ),
    ]
