# Generated by Django 4.2.1 on 2023-05-18 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_promo_promotions_alter_catalogue_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='categories',
            field=models.CharField(blank=True, max_length=60, verbose_name='CATEGORIES'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='produits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.catalogue', verbose_name='PRODUITS'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 12, 4, 46, 801701), verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 12, 4, 46, 801701), null=True, verbose_name='DATE DEBUT'),
        ),
    ]
