# Generated by Django 4.2.1 on 2023-05-18 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_catalogue_categories_alter_catalogue_produits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='promotions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.catalogue', verbose_name='PRODUITS'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='produits',
            field=models.CharField(blank=True, max_length=60, verbose_name='PRODUITS'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 12, 9, 43, 732185), verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 12, 9, 43, 732185), null=True, verbose_name='DATE DEBUT'),
        ),
    ]
