# Generated by Django 4.2.1 on 2023-05-18 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_categories_options_catalogue_promotions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='promotions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.promo', verbose_name='PROMOTIONS'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 12, 44, 3, 922703), verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 12, 44, 3, 922703), null=True, verbose_name='DATE DEBUT'),
        ),
    ]
