# Generated by Django 4.2.1 on 2023-05-18 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_promo_promo_date_end_alter_promo_promo_date_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='PRIX €'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 13, 14, 43, 98441), verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 13, 14, 43, 98441), null=True, verbose_name='DATE DEBUT'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_prix',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='PRIX €'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_remise',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Promotions %'),
        ),
    ]
