# Generated by Django 4.2.1 on 2023-05-19 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_alter_catalogue_promotions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 19, 22, 10, 23, 622508), null=True, verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 19, 22, 10, 23, 622508), null=True, verbose_name='DATE DEBUT'),
        ),
    ]
