# Generated by Django 4.2.1 on 2023-05-19 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_alter_promo_promo_date_end_alter_promo_promo_date_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 19, 22, 20, 36, 869864), null=True, verbose_name='DATE FIN'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_date_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 19, 22, 20, 36, 869864), null=True, verbose_name='DATE DEBUT'),
        ),
    ]
